### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chitgoks** [nextbike/phrase-swift#6]
Perhaps a feature that looks the same as MessageFormat where {0} {1} and {2} in the string and you supply an array of values to populate them?

**Comment by jonasvogel** [comment]
Thanks for your proposal @chitgoks. However, we are aiming to keep this similar to the linked Android/Java project (see README), so we'd rather keep placeholders as string key.
Also, an array of values will be problematic as we are using the library for localization. There are cases that the order of the placeholders would change for a phrase in a specific language, and then you wouldn't know which placeholder to match any more.
